apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: instavote
  labels:
    role: vote
spec:
  selector:
    role: vote
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: LoadBalancer